import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./Navbar";
import { Container, Theme } from "@radix-ui/themes";
import AuthProvider from "./api/auth/Provider";
import QueryClientProvider from "./QueryClientProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <Theme appearance="light" accentColor="violet">
          <QueryClientProvider>
            <AuthProvider>
              <Navbar />
              <main className="p-5">
                <Container>{children}</Container>
              </main>
            </AuthProvider>
          </QueryClientProvider>
        </Theme>
      </body>
    </html>
  );
}
